"""Add alerts related tables

Revision ID: b94f0dcac70c
Revises: c0dedcc3e3ae
Create Date: 2024-05-19 23:42:01.452671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b94f0dcac70c'
down_revision = 'c0dedcc3e3ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('notification_type', sa.Enum('STATUS', 'PERCENTAGE_USAGE', 'STORAGE', 'LOAD_AVG', 'NETWORK', name='enumtriggertypeenum'), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_trigger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('trigger_type', sa.Enum('STATUS', 'PERCENTAGE_USAGE', 'STORAGE', 'LOAD_AVG', 'NETWORK', name='enumtriggertypeenum'), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('alert_trigger_id', sa.Integer(), nullable=False),
    sa.Column('alert_notification_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_notification_id'], ['alert_notification.id'], ),
    sa.ForeignKeyConstraint(['alert_trigger_id'], ['alert_trigger.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('alert_definition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_definition_id'], ['alert_definition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert')
    op.drop_table('alert_definition')
    op.drop_table('alert_trigger')
    op.drop_table('alert_notification')
    # ### end Alembic commands ###
